main:
  prefix: "st1-tl_valt3_pretrained"
  classes: [0, 1, 2]
  epochs: 100
  batch_size: 32
  model: "resnet50"
  optim: "Adam"
  shape: [256, 256]
  patience: 5
  stop_cond: "mIoU"
  cv: 5
  src_facility: "MF0012"
  trg_facility: "MF0003"
  load_pretrained_weight: True
  pretrained_weight_dir: "/mnt/secssd/AL_SSDA_WSI_strage/s_result/checkpoints/s_MF0012_[0, 1, 2]/"
  pretrained_weight_names:
    - "cv0_epoch6.pth"
    - "cv1_epoch6.pth"
    - "cv2_epoch8.pth"
    - "cv3_epoch5.pth"
    - "cv4_epoch9.pth"
  # trg_selected_wsis:
  #   - "03_G144"
  #   - "03_G293"
  #   - "03_G109-1"
  # trg_valid_wsis:
  #   - "03_G170"
  #   - "03_G142"
  #   - "03_G143"
  result_dir: "/mnt/secssd/AL_SSDA_WSI_strage/st-tl_result/"
  
dataset:
  jb_dir: "/mnt/secssd/AL_SSDA_WSI_strage/dataset/"
  src_imgs_dir: "/mnt/secssd/SSDA_Annot_WSI_strage/mnt2/MF0012/"
  trg_imgs_dir: "/mnt/secssd/SSDA_Annot_WSI_strage/mnt2/MF0003/"

test:
  output_dir: "/mnt/secssd/AL_SSDA_WSI_strage/st-tl_result/test/"
  get_miss: False
  likelihood: False
  weight_dir:
    03_G144:
      "/mnt/secssd/AL_SSDA_WSI_strage/st-tl_result/checkpoints/st1-tl_valt3_MF0012_03_G144_[0, 1, 2]/"
  weight_names:
    03_G144: 
      - "cv0_epoch12.pth"
      - "cv1_epoch3.pth"
      - "cv2_epoch2.pth"
      - "cv3_epoch15.pth"
      - "cv4_epoch3.pth"
