main:
  prefix: "s_ada_valt20_dsampler_equal"
  classes: [0, 1, 2]
  epochs: 100
  batch_size: 16
  model: "resnet50"
  optim: "Adam"
  shape: [256, 256]
  patience: 5
  stop_cond: "mIoU"
  balance_domain: False
  cv: 5
  src_facility: "MF0012"
  trg_facility: "MF0003"
  load_pretrained_weight_E: True
  pretrained_weight_E_dir: "/mnt/secssd/AL_SSDA_WSI_MICCAI_strage/s_result/checkpoints/s_MF0012_[0, 1, 2]/"
  pretrained_weight_E_names:
    - "cv0_epoch6.pth"
    - "cv1_epoch6.pth"
    - "cv2_epoch8.pth"
    - "cv3_epoch5.pth"
    - "cv4_epoch9.pth"
  result_dir: "/mnt/secssd/AL_SSDA_WSI_MICCAI_strage/s_ada_result/"

  
dataset:
  jb_dir: "/mnt/secssd/AL_SSDA_WSI_MICCAI_strage/dataset/"
  src_imgs_dir: "/mnt/secssd/SSDA_Annot_WSI_strage/mnt2/MF0012/"
  trg_imgs_dir: "/mnt/secssd/SSDA_Annot_WSI_strage/mnt2/MF0003/"

test:
  output_dir: "/mnt/secssd/AL_SSDA_WSI_MICCAI_strage/s_ada_result/test/"
  weight_dir: "/mnt/secssd/AL_SSDA_WSI_MICCAI_strage/s_ada_result/checkpoints/s_ada_valt20_dsampler_equal_ADA_MF0012_[0, 1, 2]/"
  weight_names:
    - "cv0_E_epoch005.pth"
    - "cv1_E_epoch002.pth"
    - "cv2_E_epoch005.pth"
    - "cv3_E_epoch005.pth"
    - "cv4_E_epoch008.pth"
  
  