main:
  prefix: "st1_valt3"
  classes: [0, 1, 2]
  epochs: 100
  batch_size: 32
  model: "resnet50"
  optim: "Adam"
  shape: [256, 256]
  patience: 5
  stop_cond: "mIoU"
  balance_domain: True
  cv: 5
  src_facility: "MF0012"
  trg_facility: "MF0003"
  load_pretrained_weight: False
  # trg_selected_wsis:
  #   - "03_G144"
  #   - "03_G293"
  #   - "03_G109-1"
  # trg_valid_wsis:
  #   - "03_G170"
  #   - "03_G142"
  #   - "03_G143"
  result_dir: "/mnt/secssd/AL_SSDA_WSI_strage/st_result/"
  
dataset:
  jb_dir: "/mnt/secssd/AL_SSDA_WSI_strage/dataset/"
  src_imgs_dir: "/mnt/secssd/SSDA_Annot_WSI_strage/mnt2/MF0012/"
  trg_imgs_dir: "/mnt/secssd/SSDA_Annot_WSI_strage/mnt2/MF0003/"

test:
  output_dir: "/mnt/secssd/AL_SSDA_WSI_strage/st_result/test/"
  get_miss: False
  likelihood: False
  weight_dir:
    03_G144:
      "/mnt/secssd/AL_SSDA_WSI_strage/st_result/checkpoints/st1_valt3_MF0012_03_G144_[0, 1, 2]/"
    03_G293:
      "/mnt/secssd/AL_SSDA_WSI_strage/st_result/checkpoints/st1_valt3_MF0012_03_G293_[0, 1, 2]/"
    03_G109-1:
      "/mnt/secssd/AL_SSDA_WSI_strage/st_result/checkpoints/st1_valt3_MF0012_03_G109-1_[0, 1, 2]/"
  weight_names:
    03_G144: 
      - "cv0_epoch10.pth"
      # - "cv1_epoch3.pth"
    03_G293: 
      - "cv0_epoch6.pth"
    03_G109-1: 
      - "cv0_epoch2.pth"