main:
  prefix: "st1-ada_ep_valt3"
  classes: [0, 1, 2]
  epochs: 100
  # batch_size: 32
  # batch_size: 16
  batch_size: 8
  model: "resnet50"
  optim: "Adam"
  shape: [256, 256]
  patience: 10
  stop_cond: "mIoU"
  balance_domain: False
  cv: 5
  src_facility: "MF0012"
  trg_facility: "MF0003"
  load_pretrained_weight_E: True
  pretrained_weight_E_dir: "/mnt/secssd/AL_SSDA_WSI_strage/s_result/checkpoints/s_MF0012_[0, 1, 2]/"
  pretrained_weight_E_names:
    - "cv0_epoch6.pth"
    - "cv1_epoch6.pth"
    - "cv2_epoch8.pth"
    - "cv3_epoch5.pth"
    - "cv4_epoch9.pth"
  result_dir: "/mnt/secssd/AL_SSDA_WSI_strage/st_ada_ep_result/"
  # trg_selected_wsis:
  #   - "03_G144"
  #   - "03_G293"
  #   - "03_G109-1"
  # trg_valid_wsis:
  #   - "03_G170"
  #   - "03_G142"
  #   - "03_G143"
  
dataset:
  jb_dir: "/mnt/secssd/AL_SSDA_WSI_strage/dataset/"
  src_imgs_dir: "/mnt/secssd/SSDA_Annot_WSI_strage/mnt2/MF0012/"
  trg_imgs_dir: "/mnt/secssd/SSDA_Annot_WSI_strage/mnt2/MF0003/"

test:
  output_dir: "/mnt/secssd/AL_SSDA_WSI_strage/st_ada_ep_result/test/"
  weight_dir:
    03_G144:
      # "/mnt/secssd/AL_SSDA_WSI_strage/st_ada_result/checkpoints/st1-ada_valt3_ADA_MF0012_03_G144_[0, 1, 2]/"
  weight_names:
    03_G144: 
      # - "cv0_E_epoch003.pth"
      # - "cv1_E_epoch012.pth"
      # - "cv2_E_epoch022.pth"
      # - "cv3_E_epoch029.pth"
      # - "cv4_E_epoch001.pth"
  